platform :ios, '11.0'

target 'SportsMatching' do
  use_frameworks!
  pod 'Google-Mobile-Ads-SDK'
  pod 'JSQMessagesViewController' 
  pod 'MessageKit'
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/AdMob'
  pod 'Firebase/Firestore'
  pod 'Firebase/Functions'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'
  pod 'SVProgressHUD'
  pod 'Eureka'
  pod 'ImageRow', '~> 3.0'
  pod 'XLPagerTabStrip', '~> 8.0'
  pod 'SVProgressHUD'
  pod 'DZNEmptyDataSet'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Google'
  pod 'FirebaseUI/Facebook'
  pod 'FirebaseUI/Twitter'
  pod 'FirebaseUI/Phone'
end
